const express = require('express')
const router = express.Router()
const textsCtrl = require('../../controllers/api/texts.js')
const ensureLoggedIn = require('../../config/ensureLoggedIn.js')

router.post('/tokenize', ensureLoggedIn, textsCtrl.tokenizeText)
router.post('/add', ensureLoggedIn, textsCtrl.addNewText)
router.delete('/:id/delete', ensureLoggedIn, textsCtrl.deleteText)
router.post('/:id/save', ensureLoggedIn, textsCtrl.saveWord)
router.get('/', ensureLoggedIn, textsCtrl.getAll)
router.get('/:id', ensureLoggedIn, textsCtrl.getText)
router.get('/:id/get-saved-words', ensureLoggedIn, textsCtrl.getSavedWords)
router.post('/translate', ensureLoggedIn, textsCtrl.translateSentence)
router.post('/generate', ensureLoggedIn, textsCtrl.generateEasierText)
router.post('/:id/save-easier-text', ensureLoggedIn, textsCtrl.saveEasierText)
router.post('/:id/remove-easier-text', ensureLoggedIn, textsCtrl.removeEasierText)
router.post('/:id/archive', ensureLoggedIn, textsCtrl.archiveText)
router.post('/:id/favorite', ensureLoggedIn, textsCtrl.favoriteText)

module.exports = router